### PR TITLE
Fix #6: Send state update messages to clients with mod

### LINKED ISSUE #6: Send state update messages to clients with mod
Currently this just involves the state icon in the top left of the screen, although could involve world size so the client can figure out it's latitude + longitude.

### PR DESCRIPTION
**Pull request by cam72cam**

### CODE REVIEW

**Comment by Gegy** [comment]
Hey! Very much appreciate your contributions. :)
As of yet I don't think I'm ready to be accepting more PRs -- I'd like to get a release out first.
I'm going to merge these in now, but I'd rather for the last few tasks remaining work by myself.
Not sure if that logic makes any sense...

**Comment by cam72cam** [comment]
I definitely understand.

Do you mind if I file bugs in this repo for issues I find?  I am really looking forward to using this mod soon and would like to help in any way I can.

I can be reached at christianmesh1 at gmail if you want to chat.

**Comment by Gegy** [comment]
Do you by any chance have a Discord account? I have a channel where I'm planning to soon get the mod to beta testers for that. Otherwise, can communicate through here or email. :)

**Comment by cam72cam** [comment]
I am on discord, I'll hop on your channel if you post it here or email it

**Comment by cam72cam** [comment]
nvm, I think i joined the correct one

**Comment by Gegy** [comment]
Merging and then gonna make a quick adjustment. :)

**Pull request merged**
