### PR TITLE
Add zh_CN

### PR DESCRIPTION
**Pull request by HeartyYF**
To be honest, I can't understand “Immersed in located panorama!” .
Hope that you can explain it more detailedly.

### CODE REVIEW

**Comment by Gegy** [comment]
Thank you so much for your contribution! 😃 
Regarding "Immersed in located panorama" -- this is shown when using the Google StreetView feature. It tells that the panorama (street view images) have been shown.

**Comment by HeartyYF** [comment]
Got it.
By the way, as Google is banned by the government in China, how many features can't run without Google's service?

**Comment by Gegy** [comment]
This would only stop geocoding (place name -> latitude, longitude) and the streetview from working. I could also implement geocoding from OpenStreetMap for this purpose.

**Comment by Gegy** [comment]
Again, thanks! :)

**Pull request merged**
